on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  unit_test_job:
    name: Run unit test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'zulu'

      - name: Test with Maven
        run: mvn test