on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  unit_test_job:
    name: Run unit test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'zulu'

      - name: Install Maven
        run: sudo apt-get install -y maven

      - name: Test with Maven
        run: mvn test